name: Publish

on:
  release:
    types: [ published ]

env:
  build-output: build-output

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [win10-x64, win10-arm64]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "7.0.x"

      - name: NuGet Restore
        run: |
          dotnet restore
          dotnet tool install --global dotnet-project-licenses

      - name: Generate licences.txt
        run: dotnet-project-licenses -i DragonFruit.Kaplan.sln -u -o --output-directory DragonFruit.Kaplan --outfile licences.txt

      - name: Create output directory
        run: mkdir ${{ env.build-output }}

      - name: Publish
        run: dotnet publish --self-contained -c Release -o ${{ env.build-output }} -r ${{ matrix.arch }} -p:Version=${{ inputs.version || github.ref_name }} DragonFruit.Kaplan/DragonFruit.Kaplan.csproj

      - name: Sign file
        uses: GabrielAcostaEngler/signtool-code-sign@1.0.6
        with:
          folder: ${{ env.build-output }}
          certificate: ${{ secrets.DRAGONFRUIT_CERT_CONTENTS }}
          cert-password: ${{ secrets.DRAGONFRUIT_CERT_PASSWORD }}

      - name: Sign file (backup cert)
        if: ${{ env.CERT_CONTENTS != '' }}
        uses: GabrielAcostaEngler/signtool-code-sign@1.0.6
        with:
          folder: ${{ env.build-output }}
          certificate: ${{ secrets.BACKUP_CERT_CONTENTS }}
          cert-password: ${{ secrets.BACKUP_CERT_PASSWORD }}
        env:
          CERT_CONTENTS: ${{ secrets.BACKUP_CERT_CONTENTS }}

      - name: Rename target file
        run: Move-Item -Path ${{ env.build-output }}\DragonFruit.Kaplan.exe -Destination kaplan-${{ matrix.arch }}.exe

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: kaplan-${{ matrix.arch }}.exe
