name: Publish

on:
  release:
    types: [ published ]

env:
  build-output: build-output

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [win10-x64, win10-arm64]

    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
            7.0.x
          
      - name: Setup NuGet
        run: dotnet nuget add source --username github --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/dragonfruitnetwork/index.json"

      - name: NuGet Restore
        run: |
          dotnet restore
          dotnet tool install --global dotnet-project-licenses
          dotnet tool install --global DragonFruit.Overpass.Cli

      - name: Generate licences.txt
        run: dotnet-project-licenses -i DragonFruit.Kaplan.sln -u -o --output-directory DragonFruit.Kaplan --outfile licences.txt

      - name: Run Build Script
        run: overpass-cli
        env:
          AppName: kaplan-${{ matrix.arch }}
          Build__TargetRuntime: ${{ matrix.arch }}
          Providers__GitHub__AccessToken: ${{ secrets.GITHUB_TOKEN }}
          Certificates__DragonFruit__B64Contents: ${{ secrets.DRAGONFRUIT_CERT_CONTENTS }}
          Certificates__DragonFruit__Password: ${{ secrets.DRAGONFRUIT_CERT_PASSWORD }}
          Toolkit__signtool: C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe
